version: '3.7'

services:

  core:
    build:
      context: ./core
    container_name: core
    depends_on:
      - vector-memory
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 1865:80
    volumes:
      - ./core:/app
    command:
      - uvicorn
      - cat.main:cheshire_cat_api
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --log-config
      - ./logger.yml
      - --reload # take away in prod
    restart: unless-stopped

  admin:
    build:
      context: ./admin
    container_name: admin
    depends_on:
      - core
    ports:
      - 3000:3000
    volumes:
      - ./admin:/app
    restart: unless-stopped

  vector-memory:
    image: qdrant/qdrant:v1.1.1
    container_name: vector-memory
    expose:
      - 6333
    volumes:
      - ./long_term_memory/vector:/qdrant/storage
    restart: unless-stopped
