[project]
name = "Cheshire-Cat"
description = "Production ready AI assistant framework"
version = "1.4.8"
requires-python = ">=3.10"
license = { file="LICENSE" }
authors = [
    { name = "Piero Savastano" }, { name = "Cheshire Cat AI Contributors" }
]
dependencies = [
    "python-multipart==0.0.6",
    "pydantic==2.4.2",
    "fastapi==0.103.2",
    "websockets==10.4",
    "pandas==1.5.3",
    "scikit-learn==1.2.1",
    "qdrant_client==1.7.2",
    "langchain==0.1.4",
    "langchain-community",
    "langchain-openai",
    "langchain-google-genai",
    "openai==1.10.0",
    "cohere==4.39",
    "huggingface-hub==0.19.4",
    "beautifulsoup4==4.12.0",
    "pdfminer.six==20221105",
    "unstructured==0.5.7",
    "tiktoken==0.5.2",
    "tomli",
    "loguru==0.7.0",
    "anthropic==0.2.9",
    "gunicorn==20.1.0",
    "uvicorn[standard]==0.20.0",
    "text_generation==0.6.1",
    "tinydb==4.8.0",
    "python-slugify==8.0.1",
    "autopep8",
    "pylint",
    "perflint",
    "pylint-actions",
    "pytest",
    "httpx",
    "fastembed==0.1.3",
    "rapidfuzz==3.6.1",
]

[tool.coverage.run]
source = ["cat"]

[tool.pylint]
max-line-length = 180
disable = [
    "C0301","C0103","C0114","E0401","C0115","C0116","E1101","R0801","C0202","W0406","W1514","W0201","W0511"
]

[tool.pylint.main]
load-plugins = "pylint_actions, perflint"
