[project]
name = "Cheshire-Cat"
description = "Open source and customizable AI architecture "
version = "0.0.1"
requires-python = ">=3.10"
license = { file="LICENSE" }
authors = [
    { name = "Piero Savastano" }
]
dependencies = [
    "python-multipart==0.0.6",
    "fastapi==0.93.0",
    "fastapi-utils==0.2.1",
    "websockets==10.4",
    "SQLAlchemy==1.4.41",
    "sqlmodel==0.0.8",
    "pandas==1.5.3",
    "scikit-learn==1.2.1",
    "qdrant_client==1.1.2",
    "langchain==0.0.155",
    "openai==0.27.5",
    "cohere==4.0.4",
    "huggingface-hub==0.13.2",
    "beautifulsoup4==4.12.0",
    "pdfminer.six==20221105",
    "unstructured==0.5.7",
    "tiktoken==0.3.3",
    "tomli",
    "loguru==0.7.0",
    "anthropic==0.2.9",
    "google-generativeai==0.1.0rc3",
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "pylint"
]

[tool.coverage.run]
source = ["cat"]

[tool.pylint]
max-line-length = 180
disable = [
    "C0301","C0103","C0114","E0401","C0115","C0116","E1101","R0801","C0202","W0406","R0201","W1514","W0201","W0511"
]
