name: Admin build

on: [push]
jobs:
  Build-Admin-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        working-directory: ./admin
        run: npm ci
      - name: ğŸ§¨ï¸ Build app
        working-directory: ./admin
        run: npm run build
